// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWI9KJeKxRzID-28BsM6PB6xrAXSYmDn4',
    appId: '1:469566021708:web:bb10569a7d9f093ccc94e9',
    messagingSenderId: '469566021708',
    projectId: 'todo-app-43664',
    authDomain: 'todo-app-43664.firebaseapp.com',
    storageBucket: 'todo-app-43664.appspot.com',
    measurementId: 'G-B5GCK5N61K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83tBK_5Y8A6YpdociXohaTErKnB9eLKA',
    appId: '1:469566021708:android:3ccda0cff30efe60cc94e9',
    messagingSenderId: '469566021708',
    projectId: 'todo-app-43664',
    storageBucket: 'todo-app-43664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oEGq72GwBPnHrL2Yhlyan-lqR3FZt9c',
    appId: '1:469566021708:ios:54883772fe14992fcc94e9',
    messagingSenderId: '469566021708',
    projectId: 'todo-app-43664',
    storageBucket: 'todo-app-43664.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oEGq72GwBPnHrL2Yhlyan-lqR3FZt9c',
    appId: '1:469566021708:ios:a15f7a2f38ca4df7cc94e9',
    messagingSenderId: '469566021708',
    projectId: 'todo-app-43664',
    storageBucket: 'todo-app-43664.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
